name: NX Affected Build

env:
  NX_CLOUD_ACCESS_TOKEN: '${{ secrets.NX_CLOUD_ACCESS_TOKEN }}'

on:
  push:
    branches:
      - main

jobs:
  affected-build:
    environment: Prod
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history to ensure proper diffing

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Specify the Node.js version used in your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Determine the commits
      - name: Get Previous Commit SHA
        id: get-commit-sha
        run: echo "PREVIOUS_SHA=${{ github.event.before }}" >> $GITHUB_ENV

      # Step 5: Run NX Affected Build
      - name: Run NX Affected Build
        run: |
          npx nx affected --base=$PREVIOUS_SHA --head=$GITHUB_SHA
